name: Deploy

on:
  push:
    branches:
      - main # Set a branch to deploy when pushed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: npm install
      
      - name: Get Branch
        id: branch
        run: echo "git_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_BRANCH

      - name: Check Branch
        run: echo "${{ env.branch }}"

      - name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH

      - name: Check Hash
        run: echo "${{ env.hash }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{ env.branch }}-${{ env.hash }}
